### ISSUE TITLE
Blocked opening [...]  in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.

### ISSUE THREAD

**Issue by FilipLitwora** [fbsamples/fbinstant-samples#16]
Its propably not the right place to ask this question but i couldnt find better.
hi, im trying to implement facebook login in my "fb-insant" game, but when i click on the login button i get following error : ` Blocked opening [huge link here] in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.`
My code responsible for auth:
```
 <div id="fb-root"></div>
    <script
      async
      defer
      crossorigin="anonymous"
      src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.3&appId=myID&autoLogAppEvents=1"
    ></script>
    <div
      class="fb-login-button"
      data-width=""
      data-size="large"
      data-button-type="continue_with"
      data-auto-logout-link="false"
      data-use-continue-as="true"
    ></div>
```
Thanks in andvance

**Comment by chrishawkins** [comment]
This is intentional. The Facebook JavaScript SDK is not supported in Instant Games. For future reference I would recommend the [Instant Games community on developers.facebook.com](https://developers.facebook.com/community?sort=newest&category=334543117229184) or [StackOverflow](https://stackoverflow.com/questions/tagged/facebook-instant-games).
